#!/usr/bin/env bash
# Build Path: /app/.heroku/php/
# Build Deps: php-5.5.12

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eux

DEFAULT_VERSION="1.6.5"
dep_version=${VERSION:-$DEFAULT_VERSION}

echo "-----> Bundling Composer (${dep_version})..."

buildcurl php-min 7.0.27 | tar xz -C $OUT_PREFIX

export PATH=${OUT_PREFIX}/bin:$PATH

EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
	>&2 echo 'ERROR: Invalid installer signature'
	rm composer-setup.php
	exit 1
fi

php composer-setup.php \
  --version=${dep_version} \
  --filename=composer \
  --install-dir=${OUT_PREFIX}/bin

php ${OUT_PREFIX}/bin/composer --version
mv ${OUT_PREFIX}/bin/composer /tmp/composer
rm -rf ${OUT_PREFIX}/*
mkdir -p ${OUT_PREFIX}/bin
mv /tmp/composer ${OUT_PREFIX}/bin/composer

echo "-----> Done."
