#!/usr/bin/env bash
# Build Path: /app/.heroku/php/
# Build Deps: libraries/zlib, libraries/libmcrypt, libraries/icu, libraries/gettext

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eux

buildcurl zlib 1.2.8 | tar xz -C $OUT_PREFIX
buildcurl libmcrypt 2.5.8 | tar xz -C $OUT_PREFIX
buildcurl icu 55.1 | tar xz -C $OUT_PREFIX
buildcurl gettext-runtime 0.19.7 | tar xz -C $OUT_PREFIX

DEFAULT_VERSION="7.2.6"
dep_version=${VERSION:-$DEFAULT_VERSION}
dep_dirname=php-${dep_version}
dep_archive_name=${dep_dirname}.tar.gz
if [[ $dep_version == *alpha* ]] || [[ $dep_version == *beta* ]] || [[ $dep_version == *RC* ]]; then
    if [[ $dep_version == 5.5.* ]]; then
        dep_url=http://downloads.php.net/~jpauli/${dep_archive_name}
    elif [[ $dep_version == 5.6.* ]]; then
        dep_url=http://downloads.php.net/~tyrael/${dep_archive_name}
    elif [[ $dep_version == 7.0.* ]]; then
        dep_url=https://downloads.php.net/~ab/${dep_archive_name}
    elif [[ $dep_version == 7.1.* ]]; then
        dep_url=https://downloads.php.net/~krakjoe/${dep_archive_name}
    elif [[ $dep_version == 7.2.* ]]; then
        dep_url=https://downloads.php.net/~pollita/${dep_archive_name}
    fi
else
    dep_url=http://us1.php.net/get/${dep_archive_name}/from/this/mirror
fi

echo "-----> Building PHP ${dep_version}..."

curl -L ${dep_url} | tar xz

pushd ${dep_dirname}

configureopts=
if [[ $dep_version == 7.* ]]; then
    configureopts="\
--with-mcrypt=shared,${OUT_PREFIX} \
--enable-opcache-file\
"
else
    configureopts="\
--with-mcrypt=${OUT_PREFIX} \
--with-mysql=shared \
"
fi

export PATH=${OUT_PREFIX}/bin:$PATH
# cannot be built shared: date, ereg, opcache (always), pcre, reflection, sockets (?), spl, standard,
# sqlite3 and pdo_sqlite are on by default but we're building them shared on purpose
LD_LIBRARY_PATH=${OUT_PREFIX} ./configure \
    --prefix=${OUT_PREFIX} \
    --with-config-file-path=${OUT_PREFIX}/etc/php \
    --with-config-file-scan-dir=${OUT_PREFIX}/etc/php/conf.d \
    --disable-phpdbg \
    --enable-fpm \
    --with-bz2 \
    --with-curl \
    --with-pdo-mysql \
    --with-mysqli \
    --with-openssl \
    --with-pgsql \
    --with-pdo-pgsql \
    --with-readline \
    --enable-sockets \
    --enable-zip \
    --with-zlib \
    --with-zlib-dir=${OUT_PREFIX} \
    --enable-bcmath=shared \
    --enable-calendar=shared \
    --enable-exif=shared \
    --enable-ftp=shared \
    --with-gd=shared \
        --enable-gd-native-ttf \
        --with-freetype-dir=/usr \
        --with-jpeg-dir=/usr \
        --with-png-dir=/usr \
    --with-gettext=shared,${OUT_PREFIX} \
    --enable-intl=shared \
    --enable-mbstring=shared \
    --enable-pcntl=shared \
    --enable-shmop=shared \
    --enable-soap=shared \
    --with-sqlite3=shared \
    --with-pdo-sqlite=shared \
    --with-xmlrpc=shared \
    --with-xsl=shared \
    $configureopts
make -s -j ${JOBS:=1}
make install -s
find ${OUT_PREFIX} -type f \( -executable -o -name '*.a' \) -exec sh -c "file -i '{}' | grep -Eq 'application/x-(archive|executable|sharedlib); charset=binary'" \; -print | xargs strip --strip-unneeded
popd

rm -rf ${OUT_PREFIX}/php/man ${OUT_PREFIX}/lib/php/extensions/*/*.a

echo "-----> Preparing PECL..."
${OUT_PREFIX}/bin/pecl channel-update pecl.php.net

echo "-----> Done."
